version: '3.8'

services:
  merch_backend:
    container_name: merch_backend
    build:
      context: ./merch_service
    command: >
      sh -c 'python manage.py migrate &&
             gunicorn --workers 5 --bind 0.0.0.0:8080 merch_service.wsgi:application'
    env_file: ./merch_service/.env
    ports:
      - "8080:8080"
    volumes:
      - ./merch_service:/app
    depends_on:
      - merch_db
    networks:
      - app-network
    restart: always

  merch_frontend:
    container_name: merch_frontend
    build:
      context: ./frontend
    command: npm start
    ports:
      - "80:3000"
    depends_on:
      - merch_backend
    networks:
      - app-network
    restart: always

  merch_db:
    container_name: merch_db
    image: postgres
    env_file: ./merch_service/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  postgres-data:
