# Generated by Django 5.1.6 on 2025-02-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "create_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
